services:
  servicea:
    image: ghcr.io/lr56c/servicea:latest
    deploy:
      replicas: 2
    networks:
      - orchestrator-network

  serviceb:
    image: ghcr.io/lr56c/serviceb:latest
    deploy:
      replicas: 2
    networks:
      - orchestrator-network

  orchestrator:
    image: ghcr.io/lr56c/orchestrator:latest
    ports:
      - "80:3000"
    networks:
      - orchestrator-network
    depends_on:
      - servicea
      - serviceb

networks:
  orchestrator-network:
    external: true
